Ajustando o retorno do dto adicionando a placa do caminhão
iotruck/bino-api pull request #18
Opened 2021-05-30 02:18 UTC by jorge-lsb

2021-05-30 02:28 UTC, GabrielCarrera approved these changes
Testado, ok

2021-05-30 02:49 UTC, jose-lucas-mq approved these changes

2021-05-30 16:05 UTC, LucasFelpx commented on src/main/java/br/com/iotruck/bino/entity/Truck.java
> +    private String licensePlate;
Na classe ReadFile substituir método setLicensePlace para setLicensePlate - "linha 96"

2021-05-30 16:07 UTC, LucasFelpx commented on src/main/java/br/com/iotruck/bino/entity/Truck.java
> +    private String licensePlate;
Na DownloadController substituir o método setLicensePlace para setLicensePlate - "linha 98"

2021-05-30 16:17 UTC, LucasFelpx requested changes

2021-05-30 16:17 UTC, LucasFelpx commented on src/main/java/br/com/iotruck/bino/dto/TruckDto.java
> +    private String licensePlate;
Faltou inicializar o atributo no construtor da classe, retorno está vindo null

2021-06-01 23:17 UTC, jorge-lsb commented on src/main/java/br/com/iotruck/bino/entity/Truck.java
> +    private String licensePlate;
Ajustado

2021-06-01 23:17 UTC, jorge-lsb commented on src/main/java/br/com/iotruck/bino/dto/TruckDto.java
> +    private String licensePlate;
Ajustado

2021-06-01 23:26 UTC, jose-lucas-mq approved these changes
Carrera testou

2021-06-01 23:26 UTC, GabrielCarrera approved these changes
Testado ?ok

2021-06-01 23:29 UTC, LucasFelpx approved these changes
Testado

2021-06-01 23:29 UTC, igor-ferreira-bezerra approved these changes

2021-06-01 23:30 UTC, merged